config/routes.rb
Rails.application.routes.draw do
  root to: 'welcome#index'

  resources :states, only: [:show, :index]
  resources :legislators, only: [:show]
  resources :quotes, only: [:show]

  get '/auth/twitter', as: 'login'
  get '/auth/twitter/callback', to: 'sessions#create'
  get '/logout', to: "sessions#destroy", as: 'logout'
end

app/models/legislator.rb
class Legislator < ActiveRecord::Base
  belongs_to :state
  has_many :quotes
  has_many :words

  def cloud
    self.words.map do |word|
      { text: word.word,
        weight: word.mentions,
        link: {href: "#", class: "cloud-link"}
      }
    end
  end

  def random_quotes
    self.quotes.sample(3)
  end

  def show_party
    if party == "D"
      "Democrat"
    else
      "Republican"
    end
  end

  def show_title
    if title == "Rep"
      "Representative"
    else
      "Senator"
    end
  end
end

app/models/legislator_requester.rb
class LegislatorRequester
  include HTTParty
  base_uri 'https://congress.api.sunlightfoundation.com/'
  KEY = ENV['sunlight_key']

  def self.legislators_by_state(state)
    params = { query: {apikey: KEY,
                       state: state.name,
                       per_page: "50"}}

    self.get("/legislators?", params).parsed_response["results"]
  end

  def self.legislator_attrs(state)
    legislators_by_state(state).map do |legislator|
      { first_name: legislator["first_name"],
        last_name: legislator["last_name"],
        party: legislator["party"],
        phone: legislator["phone"],
        state_id: state.id,
        term_start: legislator["term_start"],
        term_end: legislator["term_end"],
        twitter_handle: legislator["twitter_id"],
        title: legislator["title"],
        website: legislator["website"],
        bio_id: legislator["bioguide_id"]
      }
    end
  end
end

app/models/parser.rb
class Parser
  def self.create_legislators
    State.all.each do |state|
      LegislatorRequester.legislator_attrs(state).each do |person|
        Legislator.find_or_create_by(person)
      end
    end
  end

  def self.create_leg_words
    Legislator.all.each do |leg|
      Requester.leg_word_attrs(leg).each do |word|
        Word.find_or_create_by(word)
      end
    end
  end

  def self.create_leg_quotes
    Legislator.all.each do |leg|
      leg.words.each do |word|
        Requester.leg_quote_attrs(word, leg).each do |quote|
          if quote[:body].length > 160
            quote = Quote.find_or_create_by(quote)
            quote.update_attributes(legislator: leg)
          end
        end
      end
    end
  end

  def self.check_for_quoteless_words
    Word.all.each do |word|
      word.destroy! if word.quotes.count == 0
    end
  end
end

app/models/quote.rb
class Quote < ActiveRecord::Base
  belongs_to :word
  belongs_to :legislator

  validates :speaker, presence: true
  validates :body, uniqueness: true

  def snippet
    all_words = body.delete("^a-zA-Z ").downcase.split
    return body if all_words.count <= 20

    i = all_words.index(word.word)

    #fix with validation?
    return "quote" if i.nil?
    ###

    start_i = i - 10
    end_i = i + 10

    all_words = body.split
    if start_i >= 0 && end_i <= (all_words.count - 1)
      "...#{all_words[start_i..end_i].join(" ")}..."
    elsif !(start_i >= 0)
      "#{all_words[0..end_i].join(" ")}..."
    elsif !(end_i <= (all_words.count - 1))
      "...#{all_words[start_i..-1].join(" ")}"
    end
  end
end

app/models/requester.rb
class Requester
  include HTTParty
  base_uri 'http://capitolwords.org/api/1'
  KEY = ENV['sunlight_key']

  def self.phrases_query(params)
    self.get("/phrases.json", params).to_a.map(&:symbolize_keys)
  end

  def self.text_query(params)
    query = self.get("/text.json", params).parsed_response["results"]
    query.map(&:symbolize_keys) unless query.is_a?(String)
  end

  def self.most_used_words_for_legislator(leg)
    params = { query: {apikey: KEY,
                       entity_type: "legislator",
                       entity_value: leg.bio_id,
                       sort: "count desc"}}

    filter_unwanted_words(phrases_query(params), leg.state).first(10)
  end

  def self.leg_word_attrs(leg)
    most_used_words_for_legislator(leg).map do |word_attrs|
      { word: word_attrs[:ngram],
        mentions: word_attrs[:count],
        legislator: leg,
        state: leg.state
      }
    end
  end

  def self.filter_unwanted_words(words, state)
    lame_words = ["amendment", "thing", "maybe", "...", "b", "c"]
    words.delete_if do |word|
      word[:ngram].include?(state.full_name.downcase) || lame_words.include?(word[:ngram])
    end
  end

  def self.quotes_by_legislator(word, leg)
    params = { query: { apikey: KEY,
                        phrase: word.word,
                        bioguide_id: leg.bio_id,
                        per_page: "100"}}

    text_query(params)
  end

  def self.leg_quote_attrs(word, leg)
    quotes_by_legislator(word, leg).map do |quote_attrs|
      { word: word,
        body: quote_attrs[:speaking].join(" "),
        speaker: "#{quote_attrs[:speaker_first]} #{quote_attrs[:speaker_last]}",
        bio_id: quote_attrs[:bioguide_id],
        sentiment: analyze_sentiment(quote_attrs[:speaking].join(" "))
      }
    end
  end

  def self.analyze_sentiment(quote)
    Sentimental.load_defaults
    Sentimental.new.get_score(quote)
  end
end

app/models/state.rb
class State < ActiveRecord::Base
  has_many :words
  has_many :quotes, through: :words
  has_many :legislators

  def cloud
    top_words.map do |word|
      { text: word.word,
        weight: word.mentions,
        link: {href: "#", class: "cloud-link"}
      }
    end
  end

  def top_words
    words.order(mentions: :desc).first(30)
  end

  def to_param
    name
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  def self.from_omniauth(auth_info)
    if user = find_by(uid: auth_info.extra.raw_info.user_id)
      user
    else
      create({name: auth_info.extra.raw_info.name,
          screen_name: auth_info.extra.raw_info.screen_name,
          uid: auth_info.extra.raw_info.user_id,
          oauth_token: auth_info.credentials.token,
          oauth_token_secret: auth_info.credentials.secret
        })
    end
  end
end

app/models/word.rb
class Word < ActiveRecord::Base
  belongs_to :state
  has_many :quotes
  belongs_to :legislator

  def congress_sentiments
    self.quotes.pluck(:sentiment)
  end

  def percent_positive
    unless congress_sentiments == []
      calculate_sentiment(:>)
    end
  end

  def percent_negative
    unless congress_sentiments == []
      calculate_sentiment(:<)
    end
  end

  def calculate_sentiment(operator)
    (congress_sentiments.count { |n| n.send(operator, 0) }.to_f / congress_sentiments.length.to_f * 100).to_i
  end

  def random_quotes
    self.quotes.sample(3)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end
  helper_method :current_user
end

app/controllers/legislators_controller.rb
class LegislatorsController < ApplicationController
  def show
    @user = current_user
    @legislator = Legislator.find(params[:id])
    respond_to do |format|
      format.html { render "show" }
      format.json { render json: @legislator.cloud }
    end
  end
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  def show
    @quote = Quote.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    if user = User.from_omniauth(request.env["omniauth.auth"])
      session[:user_id] = user.id
    end
    redirect_to root_path
  end

  def destroy
    session.clear
    redirect_to root_path
  end
end

app/controllers/states_controller.rb
class StatesController < ApplicationController

  def index
  end

  def show
    @state = State.find_by(name: params[:id].upcase)
    respond_to do |format|
      format.html { render "show" }
      format.json { render json: @state.cloud }
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= favicon_link_tag 'favicon.ico' %>
  <title>WhatsInAWord</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <!-- Google Fonts -->
  <link href='https://fonts.googleapis.com/css?family=Architects+Daughter' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Roboto:400,700' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Oswald:400,300' rel='stylesheet' type='text/css'>
</head>

<%= render "shared/navbar" %>

<body>
  <% unless current_page?(root_path) %>
    <%= image_tag 'donkey-elephant.png', class: 'baby-donkey-elephant' %>
  <% end %>
  <div class="container-fluid">
    <%= yield %>
  </div>
  <div id="footer">
    <%= render "shared/footer" %>
  </div>
</body>
</html>

app/views/legislators/show.html.erb
<div class="container">
  <div class="row">
    <% if @legislator.words == [] %>
      <%= render partial: '/speak_up', locals: {legislator: @legislator, user: @user} %>
    <% else %>
      <br>
      <div class="col-lg-6">
        <br>
        <div id="word-cloud" data-root="/legislators/" data-id="<%= @legislator.id %>"></div>
        <%= button_to "Back to #{@legislator.state.full_name.upcase}", state_path(@legislator.state), class: 'map-btn-2', method: :get %>
      </div>
      <div class="col-lg-1">
      </div>
      <div class="col-lg-5">
        <h1 class="quotes-list"><%= @legislator.first_name.upcase %> <%= @legislator.last_name.upcase %></h1>
        <p><strong>Party:</strong> <%= @legislator.show_party %> || <strong>Title:</strong> <%= @legislator.show_title %> || <strong>State:</strong> <%= @legislator.state.name %></p>
        <p><strong>Twitter:</strong> <%= link_to @legislator.twitter_handle, "http://twitter.com/#{@legislator.twitter_handle}" %> || <strong>Website:</strong> <%= link_to @legislator.website, @legislator.website %></p>
        <%= render partial: '/list_of_quotes', locals: { object: @legislator } %>
      </div>
    <% end %>
  </div>
</div>

app/views/quotes/show.html.erb
<div class="container">
  <div class="row">
    <br><br><br>
    <p class="quote-text">"<%= @quote.body %>" - <strong><%= @quote.speaker %></strong></p>
    <%= button_to "Back to Map", states_path, class: 'map-btn-2', method: :get %>
  </div>
</div>

app/views/shared/_footer.html.erb
<footer class="footer">
  <%= link_to "Visit Me on Github!", 'https://github.com/morganmiller' %>    |
</footer>

app/views/shared/_navbar.html.erb
<div class="container-fluid">
<div class="col-md-4">
  <%= link_to image_tag('logo.png'), root_path, class: "logo" %>
</div>


<div class="col-md-8">
  <nav>
      <p><%= link_to "map", states_path %></p>
    <% if current_user %>
      <p class="twitter"><%= link_to "logout", logout_path %></p>
    <% else %>
      <p class="twitter"><%= link_to "login with twitter", login_path %></p>
    <% end %>
  </nav>

</div>
</div>

app/views/states/_map.html.erb
<iframe src="http://createaclickablemap.com/map.php?&id=38773&online=true" width="1100" height="642" style="border: none;"></iframe>
<script>if (window.addEventListener){ window.addEventListener("message", function(event) { if(event.data.length >= 22) { if( event.data.substr(0, 22) == "__MM-LOCATION.REDIRECT") location = event.data.substr(22); } }, false); } else if (window.attachEvent){ window.attachEvent("message", function(event) { if( event.data.length >= 22) { if ( event.data.substr(0, 22) == "__MM-LOCATION.REDIRECT") location = event.data.substr(22); } }, false); } </script>

app/views/states/index.html.erb
<div class="container">
  <div class="row">
    <div id="map" style="width: 900px; height: 750px;"></div>
    <div id="clicked-state"></div>
  </div>
</div>

app/views/states/show.html.erb
<div class="container">
    <br>
    <div class="col-lg-6">
      <br>
      <div id="word-cloud" data-root="/states/" data-id="<%= @state.name %>"></div>
      <%= render partial: '/legislators', locals: { state: @state } %>
    </div>
    <div class="col-lg-1">
    </div>
    <div class="col-lg-5">
      <%= render partial: '/list_of_quotes', locals: { object: @state } %>
    </div>
</div>

app/views/welcome/index.html.erb
<%= image_tag 'donkey-elephant.png', id: 'donkey-elephant' %>
<div class="container">
<div class="col-md-4">
</div>

<div class="col-md-8">
<h1>What's in a Word?</h1>
<p>Discover what your state's legislators are talking about every day: what they say, and what they mean. Here you'll find the 2015 congressional record's most popular keywords, and the sentiments conveyed by the context. Visit the map to get started.</p>
<%= button_to "View Map", states_path, class: 'map-btn', method: :get %>
</div>

</div>